use vending_bd;

INSERT INTO producto (nombreProducto, precio, categoria) VALUES
-- BEBIDAS (25 productos)
('Agua Mineral 500ml', 1.20, 'bebida'),
('Coca-Cola Original 33cl', 1.80, 'bebida'),
('Coca-Cola Zero 33cl', 1.80, 'bebida'),
('Fanta Naranja 33cl', 1.75, 'bebida'),
('Fanta Limón 33cl', 1.75, 'bebida'),
('Sprite 33cl', 1.75, 'bebida'),
('Nestea Té Negro Limón', 1.90, 'bebida'),
('Aquarius Limón 33cl', 1.90, 'bebida'),
('Zumo de Naranja Exprimidor', 2.50, 'bebida'),
('Zumo de Piña Granini', 2.10, 'bebida'),
('Zumo de Melocotón', 1.95, 'bebida'),
('Batido de Chocolate Cacaolat', 2.20, 'bebida'),
('Batido de Vainilla Puleva', 1.85, 'bebida'),
('Batido de Fresa Puleva', 1.85, 'bebida'),
('Bebida Energética Red Bull', 2.95, 'bebida'),
('Monster Energy Original', 3.20, 'bebida'),
('Cerveza Mahou Cinco Estrellas', 1.90, 'bebida'),
('Cerveza Estrella Damm', 1.95, 'bebida'),
('Cerveza Heineken 33cl', 2.10, 'bebida'),
('Té Verde Frío con Limón', 2.30, 'bebida'),
('Café Espresso Expreso', 1.50, 'bebida'),
('Café con Leche', 1.70, 'bebida'),
('Café Capuccino', 2.40, 'bebida'),
('Agua con Gas Perrier', 2.25, 'bebida'),
('Tónica Schweppes Premium', 2.10, 'bebida'),

-- DULCES (25 productos)
('Croissant de Chocolate', 1.85, 'dulce'),
('Croissant de Mantequilla', 1.50, 'dulce'),
('Napolitana de Chocolate', 1.90, 'dulce'),
('Napolitana de Crema', 1.90, 'dulce'),
('Donut Glaseado Original', 1.60, 'dulce'),
('Donut de Chocolate', 1.75, 'dulce'),
('Berlina de Crema', 2.10, 'dulce'),
('Muffin de Arándanos', 2.25, 'dulce'),
('Muffin de Triple Chocolate', 2.40, 'dulce'),
('Palmera de Chocolate', 2.00, 'dulce'),
('Palmera de Hojaldre', 1.65, 'dulce'),
('Gofre con Chocolate Belga', 3.50, 'dulce'),
('Tortitas con Nata (3 uds)', 3.95, 'dulce'),
('Porción de Tarta de Queso', 4.50, 'dulce'),
('Porción de Tarta de Tres Chocolates', 4.25, 'dulce'),
('Porción de Red Velvet', 4.75, 'dulce'),
('Brownie de Chocolate con Nuez', 2.95, 'dulce'),
('Cookie con Chispas de Chocolate', 1.50, 'dulce'),
('Cookie Double Chocolate', 1.65, 'dulce'),
('Ensaimada Mallorquina', 1.80, 'dulce'),
('Magdalena Casera Grande', 1.20, 'dulce'),
('Macaron de Frambuesa', 1.40, 'dulce'),
('Macaron de Pistacho', 1.40, 'dulce'),
('Churros ración (4 uds)', 2.00, 'dulce'),
('Porra de Madrid (unidad)', 0.90, 'dulce'),

-- BOCATAS (25 productos)
('Bocata de Jamón Ibérico con Tomate', 5.50, 'bocata'),
('Bocata de Jamón Serrano y Queso', 4.20, 'bocata'),
('Bocata de Tortilla de Patatas', 3.80, 'bocata'),
('Bocata de Calamares a la Romana', 5.90, 'bocata'),
('Bocata de Atún con Mayonesa y Olivas', 3.95, 'bocata'),
('Bocata de Lomo con Queso Fundido', 4.50, 'bocata'),
('Bocata de Bacon con Queso Cheddar', 4.50, 'bocata'),
('Bocata Vegetal con Huevo Duro', 4.10, 'bocata'),
('Bocata de Pollo Asado con Lechuga', 4.80, 'bocata'),
('Bocata de Chistorra de Navarra', 3.90, 'bocata'),
('Bocata de Chorizo Criollo', 4.25, 'bocata'),
('Bocata de Salchichón rústico', 3.50, 'bocata'),
('Bocata de Queso Manchego Curado', 4.00, 'bocata'),
('Bocata de Sobrasada Mallorquina', 3.60, 'bocata'),
('Bocata de Mechada con Salsa BBQ', 5.20, 'bocata'),
('Bocata de Pepito de Ternera', 6.50, 'bocata'),
('Bocata de Carne y Pimientos Fritos', 5.10, 'bocata'),
('Bocata de Tortilla Francesa con Bacon', 3.75, 'bocata'),
('Bocata Caprese (Tomate Mozzarella)', 4.30, 'bocata'),
('Bocata de Lacón con Grelos', 4.90, 'bocata'),
('Bocata de Salmón Ahumado y Philadelphia', 5.80, 'bocata'),
('Bocata de Morcilla de Burgos', 3.80, 'bocata'),
('Bocata de Carne Mechada y Aguacate', 5.50, 'bocata'),
('Bocata de Pastrami y Mostaza dulce', 6.20, 'bocata'),
('Sándwich Mixto (Jamón York y Queso)', 2.80, 'bocata'),

-- GOLOSINAS (25 productos)
('Osetos de Goma Haribo 100g', 1.50, 'golosina'),
('Regaliz Rojo Relleno (unidad)', 0.25, 'golosina'),
('Regaliz Negro Tradicional', 0.25, 'golosina'),
('Lenguas de Fresa Ácidas', 0.30, 'golosina'),
('Piruleta de Corazón', 0.40, 'golosina'),
('Chupa Chups Sabor Cola', 0.50, 'golosina'),
('Chupa Chups Sabor Fresa con Nata', 0.50, 'golosina'),
('Chicles Orbit Menta (Paquete)', 1.10, 'golosina'),
('Chicles Trident Fresa (Paquete)', 1.20, 'golosina'),
('Bolsa de Gusanos Brillantes 90g', 1.40, 'golosina'),
('Bolsa de Nubes de Azúcar / Marshmallows', 1.60, 'golosina'),
('Huevo Kinder Sorpresa', 1.95, 'golosina'),
('Barrita Kinder Bueno', 1.40, 'golosina'),
('Barrita KitKat Leche', 1.30, 'golosina'),
('M&Ms Cacahuete Bolsa Mediana', 2.20, 'golosina'),
('Lacasitos Tubo Clásico', 1.15, 'golosina'),
('Conguitos Bolsa 100g', 1.75, 'golosina'),
('Caramelos Sugus Variados (Bolsa)', 1.50, 'golosina'),
('Golosina Huevo Frito (unidad)', 0.15, 'golosina'),
('Golosina Dentadura de Foamy', 0.15, 'golosina'),
('Melón de Chicle Líquido', 0.10, 'golosina'),
('Monedas de Chocolate (Malla)', 1.35, 'golosina'),
('Caramelos Halls Original', 1.25, 'golosina'),
('Pica-Pica Bolsa Polvo', 0.60, 'golosina'),
('Golosina Botella Cola Ácida', 0.15, 'golosina');